### ISSUE TITLE
Chapter 2: Ethics and Bias in AI

### ISSUE THREAD

**Issue by snehilsanyal** [snehilsanyal/computer-vision-course#1]
Hey team members, this is the issue for the second chapter of Unit 12: Ethics and Bias. 
**Main issue:** https://github.com/johko/computer-vision-course/issues/51 

### Sub-tasks:

- [x] What is Ethics and Bias in AI?
- [x] Ethical AI principles.
- [x] Asimov's principles
- [x] 23 AI principles 
- [x] UNESCO Ethical AI principles
- [x] Bias in AI.
- [x] Final structuring
- [x] PR
- [x] Reviews and Edits
- [x] Push to main

**Comment by snehilsanyal** [comment]
Merged here: https://github.com/johko/computer-vision-course/pull/174 
Closing the issue.
