### ISSUE TITLE
Chapter 7. Hugging Face's Efforts: Ethics and Society

### ISSUE THREAD

**Issue by snehilsanyal** [snehilsanyal/computer-vision-course#2]
Hey team members, this is the issue for the final chapter of Unit 12: Ethics and Bias. 
**Main issue:** https://github.com/johko/computer-vision-course/issues/51 

### Sub-tasks:

- [x]  Include efforts of Hugging Face in emphasizing Ethics for Society
- [x] Hugging Face's mission for transparency and reproducibility
- [x] 6 categories of submission of HF Spaces
- [x] Focus on CV models
- [x] Links for Discord and Spaces
- [x] Final structuring
- [x] PR
- [x] Push to main
- [x] Reviews and Edits

**Comment by snehilsanyal** [comment]
Closing the issue as content was successfully merged here: https://github.com/johko/computer-vision-course/pull/170
