### ISSUE TITLE
Chapter 4: Types of Bias in AI

### ISSUE THREAD

**Issue by snehilsanyal** [snehilsanyal/computer-vision-course#3]
Hey team members, this is the issue for the fourth chapter of Unit 12: Ethics and Bias.
Main issue: https://github.com/johko/computer-vision-course/issues/51

## Sub-tasks:
- [ ] Different sources of bias
- [ ] Focus on CV models like TTI
- [ ] Push to main
- [ ] PR
- [ ] Reviews and Edits
