### ISSUE TITLE
Chapter 5:  Bias evaluation in CV models and Metrics

### ISSUE THREAD

**Issue by snehilsanyal** [snehilsanyal/computer-vision-course#4]
Hey team members, this is the issue for the fifth chapter of Unit 12: Ethics and Bias.
Main issue: https://github.com/johko/computer-vision-course/issues/51

## Sub-tasks:
 - [ ] Case studies? Fair diffusion?
 - [ ] Standard evaluation metrics for biases in CV models.
 - [ ] Sync with chapter 4 on sources of bias.
 - [ ] Push to main.
 - [ ] PR.
 - [ ] Reviews and Edits.
